#Dockerfile
# Décrit l’image Docker de ton add-on.
# Contient les instructions pour installer toutes les dépendances, copier les fichiers nécessaires, et lancer ton script principal.
# Home Assistant construit l’add-on à partir de ce Dockerfile.

# docker build -f Dockerfile.dev -t surikat-ha .
# docker run -p 8000:8000 surikat-ha

ARG BUILD_FROM
FROM $BUILD_FROM

# Installer les dépendances pour l'add-on
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        bash && \
    rm -rf /var/lib/apt/lists/*

# Copy data for add-on
COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]

