ARG BUILD_FROM=python:3.11-slim
FROM ${BUILD_FROM}

# Installer bash, python3, pip
RUN apt-get update && apt-get install -y \
    bash \
    python3 \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copie et rend exécutable le script d'entrée
COPY run.sh /run.sh
RUN chmod +x /run.sh

COPY custom_components /app/custom_components

CMD [ "/run.sh" ]
